name: Motivation Post Automator

on:
  schedule:
    - cron: '0 5 1/2 * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    permissions:
      contents: write # history.txt save karne ke liye
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: pip install requests Pillow

      - name: Run Script
        env:
          PIXABAY_KEY: ${{ secrets.PIXABAY_KEY }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOKEN_MOTIVATION: ${{ secrets.TELEGRAM_TOKEN_MOTIVATION }}
          WEBHOOK_MOTIVATION: ${{ secrets.WEBHOOK_MOTIVATION }}
        run: python main.py

      - name: Save History to Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add history.txt || echo "No history file yet"
          git commit -m "Auto: Update history.txt with new quote" || echo "No changes to commit"
          git push
