name: Motivation Post Automator

on:
  schedule:
    # 0 5 */3 * * ka matlab:
    # Mahine ki 1, 4, 7, 10, 13, 16... tarikh ko subah 5:00 baje chalega.
    # (Do din ka gap rahega aur teesre din post hoga)
    - cron: '0 5 */3 * *'
  
  workflow_dispatch: # Manual Button click karne ke liye

jobs:
  post:
    runs-on: ubuntu-latest
    permissions:
      contents: write # history.txt save karne ke liye permission

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          PIXABAY_KEY: ${{ secrets.PIXABAY_KEY }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOKEN_MOTIVATION: ${{ secrets.TELEGRAM_TOKEN_MOTIVATION }}
          WEBHOOK_MOTIVATION: ${{ secrets.WEBHOOK_MOTIVATION }}
        run: python main.py

      - name: Save History to Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add history.txt || true
          git commit -m "Auto: Update history.txt" || echo "No changes to commit"
          git push
